# Generated by Django 4.2.14 on 2025-02-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_tourpackage_review_itinerary_alter_booking_tour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='image',
            field=models.ImageField(default='tour_images/default.jpg', upload_to='tour_images/'),
        ),
    ]
