# Generated by Django 4.2.14 on 2025-02-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_remove_tourpackage_image_url_tourpackage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
