# Generated by Django 4.2.14 on 2025-02-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_tourpackage_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='extra_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('festival', 'Festival'), ('concert', 'Concert'), ('workshop', 'Workshop'), ('conference', 'Conference'), ('marathon', 'Marathon'), ('sports', 'Sports Event'), ('exhibition', 'Exhibition')], default='festival', max_length=50),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='image',
            field=models.ImageField(default='tour_images/default.jpg', upload_to='tourimages/'),
        ),
    ]
