# Generated by Django 4.2.14 on 2025-02-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_event_extra_details_alter_event_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery',
            field=models.JSONField(blank=True, help_text='List of image URLs', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_hybrid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='video_link',
            field=models.URLField(blank=True, help_text='Optional promotional video link', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('festival', 'Festival'), ('concert', 'Concert'), ('workshop', 'Workshop'), ('conference', 'Conference'), ('marathon', 'Marathon'), ('sports', 'Sports Event'), ('exhibition', 'Exhibition'), ('nightlife', 'Nightlife'), ('tour', 'Tour'), ('webinar', 'Webinar'), ('networking', 'Networking Event')], default='festival', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='extra_details',
            field=models.JSONField(blank=True, help_text='For storing custom event data', null=True),
        ),
    ]
