# Generated by Django 4.2.23 on 2025-12-07 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tour', '0009_eventsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='planner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planned_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
