# Generated by Django 4.2.23 on 2025-12-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0010_event_planner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='join_url',
            field=models.URLField(blank=True, help_text='Public URL used for invites/QR', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='event_qr/'),
        ),
    ]
