# Generated by Django 4.2.23 on 2025-12-13 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tour', '0012_event_has_exhibitors_exhibitorspace_exhibitorbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('mc', 'MC / Host'), ('venue', 'Venue / Space'), ('catering', 'Food & Catering'), ('photography', 'Photography'), ('videography', 'Videography'), ('sound', 'Sound & Audio'), ('lighting', 'Lighting'), ('decoration', 'Decoration'), ('security', 'Security'), ('printing', 'Printing & Publishing'), ('transport', 'Transport'), ('entertainment', 'Entertainment')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_providers/')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('reviews_count', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_matches', to='tour.event')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tour.serviceprovider')),
            ],
            options={
                'unique_together': {('event', 'provider')},
            },
        ),
    ]
