# Generated by Django 4.2.23 on 2025-12-13 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tour', '0013_serviceprovider_servicematch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=100)),
                ('country', models.CharField(default='Tanzania', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('best_time_to_visit', models.CharField(blank=True, max_length=255)),
                ('highlights', models.TextField(blank=True)),
                ('avg_time_needed', models.PositiveIntegerField(default=2, help_text='Recommended days to spend')),
                ('coordinates', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='destinations/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['region', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel')], max_length=20)),
                ('price_per_liter', models.DecimalField(decimal_places=2, help_text='Price in TZS', max_digits=6)),
                ('price_per_liter_usd', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Fuel Prices',
            },
        ),
        migrations.CreateModel(
            name='TransportRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan Car'), ('suv', '4x4 SUV'), ('landcruiser', 'Toyota Land Cruiser'), ('minivan', 'Minivan (7-seater)'), ('minibus', 'Minibus (15-seater)'), ('bus', 'Coach Bus (30+ seater)')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('rate_per_day', models.DecimalField(decimal_places=2, help_text='Daily rate in USD (includes driver)', max_digits=10)),
                ('rate_per_km', models.DecimalField(decimal_places=2, default=0, help_text='Additional per-km charge if applicable', max_digits=6)),
                ('fuel_consumption', models.DecimalField(decimal_places=1, help_text='Liters per 100km', max_digits=4)),
                ('max_passengers', models.PositiveIntegerField()),
                ('ideal_for', models.CharField(blank=True, help_text="e.g., 'Safari, rough terrain'", max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['vehicle_type'],
            },
        ),
        migrations.CreateModel(
            name='TourRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=50)),
                ('tour_type', models.CharField(choices=[('budget', 'Budget'), ('mid_range', 'Mid-Range'), ('semi_luxury', 'Semi-Luxury'), ('luxury', 'Luxury')], max_length=20)),
                ('group_type', models.CharField(choices=[('solo', 'Solo Traveler'), ('couple', 'Couple'), ('family', 'Family'), ('small_group', 'Small Group (3-6)'), ('large_group', 'Large Group (7+)'), ('corporate', 'Corporate/Team')], max_length=20)),
                ('num_adults', models.PositiveIntegerField(default=2)),
                ('num_children', models.PositiveIntegerField(default=0)),
                ('budget_per_person', models.DecimalField(decimal_places=2, help_text='Budget per person in USD', max_digits=10)),
                ('budget_flexible', models.BooleanField(default=False, help_text='Is budget flexible?')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('dates_flexible', models.BooleanField(default=False)),
                ('special_requests', models.TextField(blank=True, help_text="e.g., 'Must visit Zanzibar', 'Interested in wildlife photography'")),
                ('dietary_requirements', models.CharField(blank=True, max_length=255)),
                ('mobility_requirements', models.CharField(blank=True, max_length=255)),
                ('generated_itinerary', models.TextField(blank=True, help_text='AI-generated itinerary JSON')),
                ('total_estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('itinerary_generated', 'Itinerary Generated'), ('sent_to_client', 'Sent to Client'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_requests', to=settings.AUTH_USER_MODEL)),
                ('preferred_destinations', models.ManyToManyField(blank=True, related_name='tour_requests', to='tour.destination')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HotelRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tier', models.CharField(choices=[('budget', 'Budget'), ('mid_range', 'Mid-Range'), ('semi_luxury', 'Semi-Luxury'), ('luxury', 'Luxury')], max_length=20)),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double/Twin'), ('triple', 'Triple'), ('family', 'Family Room')], default='double', max_length=20)),
                ('meal_plan', models.CharField(choices=[('bb', 'Bed & Breakfast'), ('hb', 'Half Board'), ('fb', 'Full Board'), ('ai', 'All Inclusive')], default='fb', max_length=10)),
                ('rate_low_season', models.DecimalField(decimal_places=2, help_text='Price in USD - Low Season', max_digits=10)),
                ('rate_high_season', models.DecimalField(decimal_places=2, help_text='Price in USD - High Season', max_digits=10)),
                ('high_season_start', models.CharField(default='06-01', help_text='MM-DD format', max_length=10)),
                ('high_season_end', models.CharField(default='10-31', help_text='MM-DD format', max_length=10)),
                ('contact_info', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='tour.destination')),
            ],
            options={
                'ordering': ['destination', 'tier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('activity_type', models.CharField(choices=[('park_fee', 'National Park Entry Fee'), ('game_drive', 'Game Drive'), ('walking_safari', 'Walking Safari'), ('boat_safari', 'Boat Safari'), ('balloon_safari', 'Hot Air Balloon Safari'), ('cultural_visit', 'Cultural Village Visit'), ('hiking', 'Hiking/Trekking'), ('snorkeling', 'Snorkeling'), ('diving', 'Scuba Diving'), ('spice_tour', 'Spice Tour'), ('city_tour', 'City Tour'), ('other', 'Other Activity')], max_length=20)),
                ('rate_adult', models.DecimalField(decimal_places=2, help_text='Price per adult in USD', max_digits=10)),
                ('rate_child', models.DecimalField(decimal_places=2, default=0, help_text='Price per child in USD', max_digits=10)),
                ('duration', models.CharField(blank=True, help_text="e.g., '3 hours', 'Full day'", max_length=50)),
                ('description', models.TextField(blank=True)),
                ('includes', models.TextField(blank=True, help_text="What's included in the price")),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tour.destination')),
            ],
            options={
                'ordering': ['activity_type', 'name'],
            },
        ),
    ]
