# Generated by Django 4.2.23 on 2025-12-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0014_destination_fuelprice_transportrate_tourrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourrequest',
            name='markup_percentage',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Operator profit margin %', max_digits=5),
        ),
    ]
