# Generated by Django 4.2.23 on 2025-12-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0015_add_markup_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourrequest',
            name='arrival_location',
            field=models.CharField(blank=True, help_text='Airport/City where guest arrives (e.g., JRO - Kilimanjaro, DAR - Dar es Salaam)', max_length=255),
        ),
        migrations.AddField(
            model_name='tourrequest',
            name='arrival_method',
            field=models.CharField(choices=[('flight_international', 'International Flight'), ('flight_domestic', 'Domestic Flight'), ('already_in_country', 'Already in Tanzania'), ('land_border', 'Land Border Crossing'), ('ferry', 'Ferry/Sea')], default='flight_international', max_length=30),
        ),
        migrations.AddField(
            model_name='tourrequest',
            name='current_location',
            field=models.CharField(blank=True, help_text='Where guest is currently (if already in Tanzania)', max_length=255),
        ),
        migrations.AddField(
            model_name='tourrequest',
            name='departure_location',
            field=models.CharField(blank=True, help_text='Where guest departs from (e.g., ZNZ - Zanzibar)', max_length=255),
        ),
        migrations.AddField(
            model_name='tourrequest',
            name='pickup_location',
            field=models.CharField(blank=True, help_text='Where to pick up the guest', max_length=255),
        ),
    ]
