# Generated by Django 4.2.23 on 2025-12-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0016_add_guest_location_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(choices=[('precision', 'Precision Air'), ('coastal', 'Coastal Aviation'), ('auric', 'Auric Air'), ('flightlink', 'FlightLink'), ('air_tanzania', 'Air Tanzania'), ('fastjet', 'Fastjet'), ('other', 'Other')], max_length=30)),
                ('origin', models.CharField(help_text='e.g., JRO - Kilimanjaro, DAR - Dar es Salaam', max_length=100)),
                ('origin_code', models.CharField(blank=True, help_text='Airport code e.g., JRO, DAR, ZNZ', max_length=10)),
                ('destination', models.CharField(help_text='e.g., ZNZ - Zanzibar, SEU - Seronera', max_length=100)),
                ('destination_code', models.CharField(blank=True, help_text='Airport code', max_length=10)),
                ('price_economy', models.DecimalField(decimal_places=2, help_text='Economy class price per person USD', max_digits=10)),
                ('price_business', models.DecimalField(blank=True, decimal_places=2, help_text='Business class if available', max_digits=10, null=True)),
                ('baggage_allowance', models.CharField(default='15kg', help_text='e.g., 15kg, 20kg', max_length=50)),
                ('flight_duration', models.CharField(blank=True, help_text='e.g., 1h 30m', max_length=20)),
                ('frequency', models.CharField(blank=True, help_text='e.g., Daily, Mon/Wed/Fri', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional info about this route')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Flight Rate',
                'verbose_name_plural': 'Flight Rates',
                'ordering': ['origin', 'destination'],
            },
        ),
    ]
