# Generated by Django 4.2.23 on 2025-12-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0017_add_flight_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourrequest',
            name='preferred_start_time',
            field=models.CharField(choices=[('early_morning', 'Early Morning (5:00 - 7:00 AM)'), ('morning', 'Morning (7:00 - 9:00 AM)'), ('mid_morning', 'Mid-Morning (9:00 - 11:00 AM)'), ('flexible', 'Flexible / No Preference')], default='morning', help_text='What time does the guest prefer to start each day?', max_length=20),
        ),
    ]
