# Generated by Django 4.2.23 on 2025-12-15 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tour', '0018_add_preferred_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Brief description of the package')),
                ('package_type', models.CharField(choices=[('safari', 'Safari'), ('beach', 'Beach Holiday'), ('cultural', 'Cultural Tour'), ('adventure', 'Adventure'), ('honeymoon', 'Honeymoon'), ('family', 'Family Package'), ('budget', 'Budget Package'), ('luxury', 'Luxury Package'), ('combined', 'Combined Safari & Beach'), ('other', 'Other')], default='safari', max_length=20)),
                ('duration_days', models.PositiveIntegerField(default=1, help_text='Number of days')),
                ('destinations', models.CharField(blank=True, help_text='Comma-separated list of destinations', max_length=500)),
                ('price_per_person', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_group_size', models.PositiveIntegerField(default=1)),
                ('max_group_size', models.PositiveIntegerField(default=20)),
                ('pdf_itinerary', models.FileField(help_text='Upload PDF itinerary for reference/training', upload_to='package_pdfs/')),
                ('cover_image', models.ImageField(help_text='Main image for the package', upload_to='package_images/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='package_images/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='package_images/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='package_images/')),
                ('extracted_text', models.TextField(blank=True, help_text='Text extracted from PDF for AI training')),
                ('is_analyzed', models.BooleanField(default=False, help_text='Has the PDF been analyzed?')),
                ('share_token', models.CharField(blank=True, help_text='Token for sharing with clients', max_length=50, null=True, unique=True)),
                ('is_public', models.BooleanField(default=False, help_text='Show in public marketplace')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uploaded Package',
                'verbose_name_plural': 'Uploaded Packages',
                'ordering': ['-created_at'],
            },
        ),
    ]
