# Generated by Django 4.2.23 on 2025-12-15 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tour', '0019_add_uploaded_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tour operator name', max_length=255)),
                ('base_url', models.URLField(help_text='Website base URL')),
                ('is_active', models.BooleanField(default=True)),
                ('requires_javascript', models.BooleanField(default=False, help_text='Use Selenium/Playwright if True')),
                ('rate_limit_seconds', models.PositiveIntegerField(default=5, help_text='Seconds between requests')),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('total_scraped', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Scraping Source',
                'verbose_name_plural': 'Scraping Sources',
            },
        ),
        migrations.AlterField(
            model_name='uploadedpackage',
            name='cover_image',
            field=models.ImageField(upload_to='package_images/'),
        ),
        migrations.AlterField(
            model_name='uploadedpackage',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='uploadedpackage',
            name='is_analyzed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='uploadedpackage',
            name='pdf_itinerary',
            field=models.FileField(upload_to='package_pdfs/'),
        ),
        migrations.CreateModel(
            name='TrainingExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='training_exports/')),
                ('record_count', models.PositiveIntegerField()),
                ('export_format', models.CharField(default='jsonl', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher = processed first')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='tour.scrapingsource')),
            ],
            options={
                'verbose_name': 'Scrape Queue Item',
                'verbose_name_plural': 'Scrape Queue',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('scraped', 'Web Scraped'), ('uploaded', 'PDF Upload'), ('manual', 'Manual Entry')], default='scraped', max_length=20)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('raw_html', models.TextField(blank=True, help_text='Original HTML if scraped')),
                ('raw_text', models.TextField(help_text='Extracted plain text')),
                ('page_title', models.CharField(blank=True, max_length=500)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tour.scrapingsource')),
                ('uploaded_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_itineraries', to='tour.uploadedpackage')),
            ],
            options={
                'verbose_name': 'Raw Itinerary',
                'verbose_name_plural': 'Raw Itineraries',
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_instruction', models.TextField(help_text='The user instruction that would produce this itinerary')),
                ('title', models.CharField(max_length=500)),
                ('destination_country', models.CharField(blank=True, max_length=100)),
                ('destinations', models.JSONField(default=list, help_text='List of specific destinations/parks')),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('budget_level', models.CharField(blank=True, choices=[('budget', 'Budget'), ('mid_range', 'Mid-Range'), ('luxury', 'Luxury'), ('ultra_luxury', 'Ultra Luxury')], max_length=20)),
                ('estimated_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trip_type', models.CharField(blank=True, choices=[('safari', 'Safari'), ('beach', 'Beach Holiday'), ('cultural', 'Cultural Tour'), ('adventure', 'Adventure'), ('honeymoon', 'Honeymoon'), ('family', 'Family Trip'), ('wildlife', 'Wildlife Photography'), ('trekking', 'Trekking/Hiking'), ('combined', 'Combined Tour')], max_length=20)),
                ('group_type', models.CharField(blank=True, help_text='e.g., Couple, Family, Solo', max_length=100)),
                ('itinerary_json', models.JSONField(default=dict, help_text='Day-by-day structured itinerary')),
                ('inclusions', models.JSONField(default=list)),
                ('exclusions', models.JSONField(default=list)),
                ('accommodations', models.JSONField(default=list, help_text='List of hotels/lodges used')),
                ('activities', models.JSONField(default=list, help_text='List of activities')),
                ('training_json', models.JSONField(default=dict, help_text='Complete JSON for model training')),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision')], default='pending_review', max_length=20)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('gpt_model_used', models.CharField(blank=True, max_length=50)),
                ('gpt_processing_time', models.FloatField(blank=True, help_text='Seconds', null=True)),
                ('gpt_tokens_used', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_itinerary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processed', to='tour.rawitinerary')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_itineraries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processed Itinerary',
                'verbose_name_plural': 'Processed Itineraries',
                'ordering': ['-created_at'],
            },
        ),
    ]
